method: metaavatar
data:
  dim: 3
  dataset: raw_scan
  path: /local/home/zhqian/data/ZJU-MoCap
  input_type: pointcloud
  input_pointcloud_n: 5000
  input_pointcloud_noise: 0.0
  use_aug: true
  normalized_scale: true
  train_split: ['CoreView_313']
  val_split: ['CoreView_313']
  test_split: ['CoreView_313']
model:
  encoder: pointnet_conv
  skinning_decoder: unstructured_groupnorm
  decoder: hyper_bvp
  encoder_kwargs: {'hidden_dim': 256, 'scatter_type': mean, 'unet': true, 'unet3d': false, 'plane_type': ['xz', 'xy', 'yz'], 'plane_resolution': 64, 'padding': 1.0}
  decoder_kwargs: {'in_features': 3, 'num_hidden_layers': 5, 'hierarchical_pose': true, 'hyper_in_ch': 144, 'initial_model': out/meta-avatar/conv-unet-plane64x3_CAPE-SV_keep-aspect_stage1-inner-1e-4-outer-1e-5_1gpus/model_best.pt}
  skinning_decoder_kwargs: {'hidden_size': 1024, 'gn_groups': 32}
  keep_aspect_ratio: true
  c_dim: 96
  z_dim: 0
  skinning_net1: out/meta-avatar/conv-unet-plane64x3_CAPE-SV_keep-aspect_stage0-separate-skinning_1gpus/model_best.pt
  skinning_net2: out/meta-avatar/conv-unet-plane64x3_CAPE_keep-aspect_stage0-separate-skinning_1gpus/model_best.pt
training:
  gpus: [0]
  out_dir:  out/meta-avatar/conv-unet-plane64x3_ZJU-MoCap_keep-aspect_stage2-inner-1e-6-outer-1e-6_1gpus
  batch_size: 0
  inner_batch_size: 6
  model_selection_metric: loss
  model_selection_mode: minimize
  visualize_every: 0
  validate_every: 0
  backup_every: 0
  max_epochs: 50
  stage: meta-hyper
  lr: 0.000001
  inner_lr: 0.000001
  meta_learner: reptile
  no_test_loss: true
test:
  threshold: 0.5
  # model_file: model.pt
  optim_iterations: 128
generation:
  batch_size: 1
  refine: false
  vis_n_outputs: 10000
  n_x: 128
  n_z: 1
  resolution_0: 256
  upsampling_steps: 0
