method: onet
data:
  path: data/AMASS
  dataset: amass_motion
  use_aug: false
  normalized_scale: false
  use_mask: false
  input_type: pcl_seq
  train_split: train
  val_split: val
  test_split: test
  train_cloth_types: null
  val_cloth_types: null
  test_cloth_types: null
  train_action_names: null
  val_action_names: null
  test_action_names: null
  dim: 3
  single_view: false
  points_subsample: 1024
  n_points_corr: 2048
  points_uniform_ratio: 0.5
  n_training_points: 512
  input_pointcloud_n: 300
  input_pointcloud_noise: 0.001
  use_raw_scans: false
model:
  decoder: cbatchnorm
  encoder: pointnet_resnet
  encoder_temporal: pointnet_resnet
  velocity_field: concat
  velocity_field_static: null
  encoder_latent: null
  encoder_latent_temporal: null
  transform_field: ptf_groupnorm
  smpl_estimator: oneshot
  decoder_kwargs: {}
  transform_field_kwargs: {}
  smpl_estimator_kwargs: {}
  encoder_kwargs: {}
  encoder_latent_kwargs: {}
  encoder_temporal_kwargs: {}
  velocity_field_kwargs: {}
  velocity_field_static_kwargs: {}
  encoder_latent_temporal_kwargs: {}
  learn_embedding: false
  # multi_gpu: false
  gpus: [0]
  # use_latent_pose: false
  latent_length: 50
  c_dim: 512
  z_dim: 0
  ode_solver: dopri5
  ode_step_size: null
  use_adjoint: true
  rtol: 0.001
  atol: 0.00001
  vae_beta: 0.0001
  loss_corr: false
  loss_corr_bw: false
  loss_recon: true
  initialize_from: null
  initialization_file_name: model_best.pt
  c_dim: 512
  z_dim: 0
  use_camera: false
  dmc_weight_prior: 10.
  keep_aspect_ratio: true
  simple_concat: false
  skinning_net1: null
  skinning_net2: null
  minimal_skinning_encoding: false
training:
  out_dir:  out/default
  batch_size: 16
  inner_batch_size: 12
  print_every: 10
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  model_selection_metric: iou
  model_selection_mode: maximize
  n_eval_points: 5000
  skinning_weight: 0.5
  corr_weight: 1.0
  max_iterations: -1
  max_epochs: -1 
  corr_loss_all_points: true
  lr: 0.0001
  inner_lr: 0.0001
  meta_SGD: false
  proj_thr: 0.02
  meta_learner: reptile
  no_test_loss: false
  optim_iterations: 24
test:
  threshold: 0.5
  model_file: model_best.pt
  optim_iterations: 128
generation:
  interpolate: false
  fix_z: false
  fix_zt: false
  n_time_steps: 17
  padding: 0.1
  mesh_color: true
  only_end_time_points: false
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  use_sampling: false
  resolution_0: 32
  upsampling_steps: 2
  simplify_nfaces: null
  copy_groundtruth: false
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
preprocessor:
  type: null
  config: ""
  model_file: null
